name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 24.4
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master
    - uses: actions/checkout@v1
    - name: Install
      run: 'cask install'
    - name: Run tests
      run: 'cask exec ert-runner'
